CREATE OR REPLACE FUNCTION FUNC_MINIMUM(VARIADIC ARR 
NUMERIC[]) RETURNS NUMERIC AS $$ 
	DECLARE min_val NUMERIC;
	BEGIN
	SELECT
	    MIN(value) INTO min_val
	FROM unnest(arr) AS value;
	RETURN min_val;
	END;
	$$ LANGUAGE 
PLPGSQL; 

SELECT func_minimum(VARIADIC arr => ARRAY[10.0, -1.0, 5.0, 4.4]);